### ISSUE TITLE
Error ord() expected string

### ISSUE THREAD

**Issue by toothrobber** [humberry/hexviewer#7]
I am new to Python, not sure about the string vs int in the Python language 

I found my problem, the issue is that I had version 3 of Python set, running with version 2.7 the code worked.

Error!
File = /private/var/mobile/Containers/Shared/AppGroup/2305D04D-1CFC-4AB7-9090-7C26133C1A88/Pythonista3/Documents/csvdata.txt
Error = ord() expected string of length 1, but int found

**Comment by humberry** [comment]
You're right some things have changed with Python 3. If you have time feel free to fix it and send a pull request (universal code or new file). [Here](http://python3porting.com/problems.html) you can find some hints.
